-- 코드를 입력하세요
WITH A AS(
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL BETWEEN 1 AND 24
),
B AS(
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
    ORDER BY TO_CHAR(DATETIME, 'HH24')
)
SELECT A.HOUR, NVL(B.COUNT, '0')
FROM A LEFT JOIN B ON A.HOUR = B.HOUR
ORDER BY A.HOUR